# This is a basic workflow to help you get started with Actions

name: 'Push Helm Chart'

on:
  pull_request:
    types: [closed]
    branches:
      - master
    
jobs:
  push-helm-chart:
    runs-on: ubuntu-latest
    name: Push helm chart to CodeFresh repo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push Helm Chart to ChartMuseum
        uses: bsord/cf-helm-push@v14.0.8
        with:
          access-token: ${{ secrets.CF_API_KEY }}
          repository-url: 'cm://helm.bsord.dev/fairbanks.io/default'
          force: true
          chart-folder: chart
