# This is a basic workflow to help you get started with Actions

name: 'Push Helm Chart'

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        
jobs:
  push-helm-chart:
    runs-on: ubuntu-latest
    name: Push helm chart to CodeFresh repo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push Helm Chart to ChartMuseum
        uses: bsord/cf-helm-push@v14.0.3
        with:
          access-token: ${{ secrets.CF_API_KEY }}
          repository-url: 'cm://h.cfcr.io/fairbanks.io/default'
